dist: xenial
language: minimal
sudo: required

services:
  - docker

before_install:
  # none

addons:
  apt:
    packages:
      - docker-ce

env:
  - TARGET_DIST=ubuntu TARGET_VER=1804
  - TARGET_DIST=ubuntu TARGET_VER=1804-clang  
  - TARGET_DIST=ubuntu TARGET_VER=1604
  - TARGET_DIST=debian TARGET_VER=8

script:
  - mkdir ../workdir
  - cd ../workdir
  - mv ../OpenRTM-aist .

  - export IMAGE_NAME=openrtm:${TARGET_DIST}-${TARGET_VER}
  - docker build -f OpenRTM-aist/scripts/${TARGET_DIST}_${TARGET_VER}/Dockerfile . -t ${IMAGE_NAME}
